feat: support static connection info
GoogleCloudPlatform/alloydb-python-connector pull request #406
Opened 2024-12-24 03:38 UTC by rhatgadkar-goog

2025-01-30 13:42 UTC, jackwotherspoon commented on google/cloud/alloydb/connector/async_connector.py
> +        static_conn_info = kwargs.pop("static_conn_info", self._static_conn_info)
If this is purely used for testing we should limit the public exposure...

is this needed here? Are you planning to pass the `static_conn_info` to `Connector()` initialization or to `connector.connect()`??

2025-01-30 13:49 UTC, jackwotherspoon commented
@rhatgadkar-goog With no PR description I do not yet fully see the benefit or use-case of this change...

Is it to allow to customize the certs more easily?

2025-01-30 16:34 UTC, enocom commented
This is a peer of what we did in Go: https://github.com/GoogleCloudPlatform/alloydb-go-connector/blob/main/options.go#L218-L246

The primary use case is for development-time convenience by removing the control plane from the connection flow. I would guess there aren't many production uses for this, but it's a big convenience for development.

2025-01-31 02:26 UTC, rhatgadkar-goog commented on tests/unit/conftest.py
> +        with context.wrap_socket(sock, server_side=True) as ssock:
This change is needed to run multiple tests that use the same `proxy_server` fixture. Without it, only 1 test can successfully run. The other tests fail with "Connection refused" errors.

2025-01-31 02:34 UTC, rhatgadkar-goog commented on tests/unit/conftest.py
> +    thread.join(0.1) # wait 100ms to allow the proxy server to start
This change is required when implementing the change above (swapping the order of `while True` and `with context.wrap_socket`) to prevent the test from hanging

2025-01-31 03:28 UTC, rhatgadkar-goog commented on google/cloud/alloydb/connector/async_connector.py
> +        static_conn_info = kwargs.pop("static_conn_info", self._static_conn_info)
Yes, it's purely used for testing. I see your point about limiting public exposure. I've only included the `static_conn_info` in the constructor now and not in the `connector.connect()` function.

2025-02-03 22:37 UTC, enocom commented on google/cloud/alloydb/connector/async_connector.py
> +        static_conn_info (io.TextIOBase): A file-like JSON object that contains
Since the async connector isn't working, shall we just avoid adding this parameter?

If we never need async support in sandbox, we can revisit this decision. For now, having python support for sandbox is purely a development-time convenience.

2025-02-03 22:37 UTC, enocom commented on tests/unit/conftest.py
> +    thread.join(0.1)  # wait 100ms to allow the proxy server to start
Shall we pull `0.1` out into a constant and possibly bump it to 1000ms just to avoid any flaky tests (trading a slight increase in test runtime for stability)?

2025-02-03 22:37 UTC, enocom commented on google/cloud/alloydb/connector/connector.py
> +        static_conn_info: Optional[io.TextIOBase] = None,
Any thoughts on why we prefer io.TextIOBase instead of io.StringIO?

2025-02-04 02:17 UTC, rhatgadkar-goog commented on google/cloud/alloydb/connector/connector.py
> +        static_conn_info: Optional[io.TextIOBase] = None,
A file-type object is type `io.TextIOWrapper`. From the Python repl:
```
(py-dev-env) rhatgadkar@rhatgadkar:~$ python
Python 3.11.9 (main, Jun 19 2024, 00:38:48) [GCC 13.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> open('static.json', 'r')
<_io.TextIOWrapper name='static.json' mode='r' encoding='UTF-8'>
```

`io.TextIOWrapper` inherits `io.TextIOBase`: https://docs.python.org/3/library/io.html#io.TextIOWrapper. `io.StringIO` also inherits `io.TextIOBase`: https://docs.python.org/3/library/io.html#io.StringIO.

So to support both cases of the `static.json`: (1) the string returned by `write_static_info()` and (2) inputting a file-like object, we should use `io.TextIOBase`.

2025-02-04 02:58 UTC, rhatgadkar-goog commented on google/cloud/alloydb/connector/connector.py
> +        cache: Union[RefreshAheadCache, LazyRefreshCache, StaticConnectionInfoCache]
Done. I've added a `types.py` file, where I've added a `CacheTypes` variable.

2025-02-04 02:58 UTC, rhatgadkar-goog commented on tests/unit/conftest.py
> +    thread.join(0.1)  # wait 100ms to allow the proxy server to start
Done

2025-02-04 02:58 UTC, rhatgadkar-goog commented on google/cloud/alloydb/connector/async_connector.py
> +        static_conn_info (io.TextIOBase): A file-like JSON object that contains
Makes sense. I removed it.

2025-02-04 14:57 UTC, jackwotherspoon requested changes
I still am not sold on this approach being the best one. There are ways to load static info without changes to the public interface. I would highly suggest looking into them more instead of just doing this purely because  the Go Connector did it this way.

One example being I don't think it would be much effort to make a `SandBoxClient` testing object similar to `FakeAlloyDBClient` that is wired up to always return static connection info.
https://github.com/GoogleCloudPlatform/alloydb-python-connector/blob/397d34f467dcbe378338048f021f5634a8543276/tests/unit/mocks.py#L198 

This way you could write a simple private helper method `_create_sandbox_connector` that would look something like this:

```python
def _create_sandbox_connector(static_info, *args, **kwargs):
    connector = Connector(*args, **kwargs)
    client = SandBoxClient(static_info)
    connector._client = client
    return connector
```

This lets you not mess with the public interface for something that will never be used by customers, reducing confusion in the code and making things more readable.

2025-02-04 14:57 UTC, jackwotherspoon commented on google/cloud/alloydb/connector/static.py
> +    This static connection info should hold JSON with the following format:
please clearly state this meant for testing purposes and not intended for external (public) use

2025-02-04 14:57 UTC, jackwotherspoon commented on tests/unit/conftest.py
> +DELAY: Final[float] = 1.0
nit: this is up to you to decide so do with it whatever you feel is best

I am personally not a fan of using `Final` to type hint constants. I find it makes things less readable. Anyone that sees a variable be all capitals will know it is a constant.

2025-02-04 14:57 UTC, jackwotherspoon commented on tests/unit/conftest.py
> +    thread.join(DELAY)  # add a delay to allow the proxy server to start
It has been a while since I've looked at this piece of code, can you explain why you have removed the `yield` for this new setup?

Using `yield` guarantees the fixture is ready for use when it is passed to a test or session. Then when it is done, it will run the code after the `yield`...

Calling `thread.join` right away will block the main thread until `thread` is terminated. This may be okay as it will block until the pytest session is done. But you may also find blocking the main thread to cause issues or hang in the future.

2025-02-04 16:16 UTC, enocom commented on google/cloud/alloydb/connector/static.py
> +    This static connection info should hold JSON with the following format:
We could just match https://github.com/GoogleCloudPlatform/alloydb-go-connector/blob/main/options.go#L218-L223 here.

2025-02-04 20:55 UTC, enocom commented on google/cloud/alloydb/connector/connector.py
> +        static_conn_info: Optional[io.TextIOBase] = None,
Perfect. That sounds like exactly what we want -- letting people pass in a file or a string.

2025-02-07 17:48 UTC, rhatgadkar-goog commented on tests/unit/conftest.py
> +    thread.join(DELAY)  # add a delay to allow the proxy server to start
I explained it in a previous comment [here](https://github.com/GoogleCloudPlatform/alloydb-python-connector/pull/406#discussion_r1936599481).

I need it, because the test was hanging after doing the change I described [here](https://github.com/GoogleCloudPlatform/alloydb-python-connector/pull/406#discussion_r1936595386) (swapping the order of `while True` and `with context.wrap_socket`).

The way I understand it is that `thread.join` will block until `thread` is terminated. But the `thread`, which runs `start_proxy_server`, will never be terminated, because it contains a `while True` loop.

2025-02-07 18:12 UTC, rhatgadkar-goog commented
> I still am not sold on this approach being the best one. There are ways to load static info without changes to the public interface. I would highly suggest looking into them more instead of just doing this purely because the Go Connector did it this way.
> 
> One example being I don't think it would be much effort to make a `SandBoxClient` testing object similar to `FakeAlloyDBClient` that is wired up to always return static connection info.
> 
> https://github.com/GoogleCloudPlatform/alloydb-python-connector/blob/397d34f467dcbe378338048f021f5634a8543276/tests/unit/mocks.py#L198
> 
> This way you could write a simple private helper method `_create_sandbox_connector` that would look something like this:
> 
> ```python
> def _create_sandbox_connector(static_info, *args, **kwargs):
>     connector = Connector(*args, **kwargs)
>     client = SandBoxClient(static_info)
>     connector._client = client
>     return connector
> ```
> 
> This lets you not mess with the public interface for something that will never be used by customers, reducing confusion in the code and making things more readable.

We discussed that for now we will keep the current approach of having the `static_conn_info` as an argument in the public interface. If in the future, we find that there are more dev-only parameters, we can decide to not include dev-only parameters in the public interface and use an approach similar to this.

2025-02-07 18:13 UTC, rhatgadkar-goog commented on tests/unit/conftest.py
> +DELAY: Final[float] = 1.0
I agree with you. I also never see `Final` being used in most Python code. I have removed the `Final` type hint.

2025-02-07 18:13 UTC, rhatgadkar-goog commented on google/cloud/alloydb/connector/static.py
> +    This static connection info should hold JSON with the following format:
Done. I've added a comment in `static.py` and a comment in the constructor of `Connector`.

2025-02-07 21:52 UTC, enocom approved these changes

2025-02-11 20:18 UTC, jackwotherspoon approved these changes
LGTM ✅

2025-02-11 20:40 UTC, merged